name: Deploy website to GitHub Pages

env:
  WC_HUGO_VERSION: '0.126.3'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache_runner/
          key: ${{ runner.os }}-hugomod-${{ hashFiles('website-main/**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          cd website-main
          hugo --minify --baseURL "${{ github.repository_url }}/website-main/"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: website-main/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: website-main/public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website-main/public


